# --------------------------------------------------------
# These properties are the local development properties.
#
# Spring boot uses this file when the application is launched
# with the root of the project set as the working directory.
# These properties take precendence over the classpath
# application.yml.
#
# Using gradle from the commandline means the working
# directory is by defaul the project root.
#
# Using Intellij you need to setup your run config so the
# working directory is the project root.
# --------------------------------------------------------
server:
  port: 8085

security:
  basic:
    enabled: "true"
  user:
    name: "admin"
    password: "admin"

spring:
  session:
    enabled: "${SESSION_CLUSTER_ENABLED:true}"

irj:
  systemUserName: "item-report-job"
  systemFullName: "Item Report Job"

tasks:
  reportSchedule: "0 */5 * * * *"

itembank:
  host: "https://gitlab-dev.smarterbalanced.org"
  accessToken: "${GITLAB_ACCESS_TOKEN}"
  user: "${GITLAB_USER}"
  password: "${GITLAB_PASSWORD}"
  group: "${GITLAB_GROUP}"
  localBaseDir: "${HOME}/ItemBankIRJ"
  apiVersion: "/api/v4"
  bankKey: "187"
  lockSectionMaxRetries: "10"
  lockSectionRetryDelayMillis: "2000"
  randomizeItemClone: false
  reportRepoName: "ItemBankReports"

logging:
  level:
    org:
      opentestsystem:
        ap:
          irj: DEBUG
          common: WARN